### ISSUE TITLE
Getting issues on first run with ./quick_start.sh

### ISSUE THREAD

**Issue by OrrnobMahmud** [paulpierre/informer#10]
`<pre>usage: venv [-h] [--system-site-packages] [--symlinks | --copies] [--clear]
            [--upgrade] [--without-pip] [--prompt PROMPT] [--upgrade-deps]
            ENV_DIR [ENV_DIR ...]
venv: error: the following arguments are required: ENV_DIR
./quick_start.sh: line 11: venv/bin/activate: No such file or directory
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: SQLAlchemy==1.3.11 in /home/mahmud/.local/lib/python3.9/site-packages (from -r requirements.txt (line 1)) (1.3.11)
Requirement already satisfied: sqlalchemy-migrate==0.13.0 in /home/mahmud/.local/lib/python3.9/site-packages (from -r requirements.txt (line 2)) (0.13.0)
Requirement already satisfied: Telethon==1.23.0 in /home/mahmud/.local/lib/python3.9/site-packages (from -r requirements.txt (line 3)) (1.23.0)
Requirement already satisfied: mysql-connector-python==8.0.18 in /home/mahmud/.local/lib/python3.9/site-packages (from -r requirements.txt (line 4)) (8.0.18)
Requirement already satisfied: gspread==3.1.0 in /home/mahmud/.local/lib/python3.9/site-packages (from -r requirements.txt (line 5)) (3.1.0)
Requirement already satisfied: oauth2client==4.1.3 in /home/mahmud/.local/lib/python3.9/site-packages (from -r requirements.txt (line 6)) (4.1.3)
Requirement already satisfied: python-dotenv==0.19.0 in /home/mahmud/.local/lib/python3.9/site-packages (from -r requirements.txt (line 7)) (0.19.0)
Requirement already satisfied: requests&gt;=2.2.1 in /usr/lib/python3.9/site-packages (from gspread==3.1.0-&gt;-r requirements.txt (line 5)) (2.26.0)
Requirement already satisfied: protobuf&gt;=3.0.0 in /home/mahmud/.local/lib/python3.9/site-packages (from mysql-connector-python==8.0.18-&gt;-r requirements.txt (line 4)) (3.17.3)
Requirement already satisfied: rsa&gt;=3.1.4 in /home/mahmud/.local/lib/python3.9/site-packages (from oauth2client==4.1.3-&gt;-r requirements.txt (line 6)) (4.7.2)
Requirement already satisfied: pyasn1&gt;=0.1.7 in /home/mahmud/.local/lib/python3.9/site-packages (from oauth2client==4.1.3-&gt;-r requirements.txt (line 6)) (0.4.8)
Requirement already satisfied: pyasn1-modules&gt;=0.0.5 in /home/mahmud/.local/lib/python3.9/site-packages (from oauth2client==4.1.3-&gt;-r requirements.txt (line 6)) (0.2.8)
Requirement already satisfied: httplib2&gt;=0.9.1 in /home/mahmud/.local/lib/python3.9/site-packages (from oauth2client==4.1.3-&gt;-r requirements.txt (line 6)) (0.19.1)
Requirement already satisfied: six&gt;=1.6.1 in /usr/lib/python3.9/site-packages (from oauth2client==4.1.3-&gt;-r requirements.txt (line 6)) (1.16.0)
Requirement already satisfied: pbr&gt;=1.8 in /home/mahmud/.local/lib/python3.9/site-packages (from sqlalchemy-migrate==0.13.0-&gt;-r requirements.txt (line 2)) (5.6.0)
Requirement already satisfied: Tempita&gt;=0.4 in /home/mahmud/.local/lib/python3.9/site-packages (from sqlalchemy-migrate==0.13.0-&gt;-r requirements.txt (line 2)) (0.5.2)
Requirement already satisfied: sqlparse in /home/mahmud/.local/lib/python3.9/site-packages (from sqlalchemy-migrate==0.13.0-&gt;-r requirements.txt (line 2)) (0.4.1)
Requirement already satisfied: decorator in /home/mahmud/.local/lib/python3.9/site-packages (from sqlalchemy-migrate==0.13.0-&gt;-r requirements.txt (line 2)) (5.0.9)
Requirement already satisfied: pyaes in /home/mahmud/.local/lib/python3.9/site-packages (from Telethon==1.23.0-&gt;-r requirements.txt (line 3)) (1.6.1)
Requirement already satisfied: pyparsing&lt;3,&gt;=2.4.2 in /usr/lib/python3.9/site-packages (from httplib2&gt;=0.9.1-&gt;oauth2client==4.1.3-&gt;-r requirements.txt (line 6)) (2.4.7)
Requirement already satisfied: chardet&gt;=3.0.2 in /usr/lib/python3.9/site-packages (from requests&gt;=2.2.1-&gt;gspread==3.1.0-&gt;-r requirements.txt (line 5)) (4.0.0)
Requirement already satisfied: idna&gt;=2.5 in /usr/lib/python3.9/site-packages (from requests&gt;=2.2.1-&gt;gspread==3.1.0-&gt;-r requirements.txt (line 5)) (3.2)
Requirement already satisfied: urllib3&gt;=1.21.1 in /usr/lib/python3.9/site-packages (from requests&gt;=2.2.1-&gt;gspread==3.1.0-&gt;-r requirements.txt (line 5)) (1.26.6)
INFO:root:env_file: informer.env
INFO:telethon.crypto.aes:libssl detected, it will be used for encryption
Traceback (most recent call last):
  File &quot;/home/mahmud/Downloads/informer-master/app/bot.py&quot;, line 33, in &lt;module&gt;
    account_id = sys.argv[1]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &quot;/home/mahmud/Downloads/informer-master/app/bot.py&quot;, line 35, in &lt;module&gt;
    raise Exception(&apos;informer.py &lt;account_id&gt; - account_id is a required param&apos;)
Exception: informer.py &lt;account_id&gt; - account_id is a required param
</pre>`

**Comment by 0xtwoface** [comment]
I’m facing with the same problem tried so many things but couldnt pass this error

**Comment by SrJok3s** [comment]
Same problem here @paulpierre

**Comment by benichmt1** [comment]
I believe the intention is you are supposed to alter that single line in `quick_start.sh`
```
#run the bot
python3 bot.py <your-id>

```
I'm still running into some docker networking issues. I believe the reference here `docker.for.mac.localhost` has been superceded.

**Comment by 1j0ker** [comment]
the same problem that i sloved by modify  **`quick_start.sh`** in line8:
`python3 -m venv venv`

please insure your python3 version >3.7

**Comment by 1j0ker** [comment]
> `
> 
> usage: venv [-h] [--system-site-packages] [--symlinks | --copies] [--clear]
> 
> [--upgrade] [--without-pip] [--prompt PROMPT] [--upgrade-deps]
> 
> ENV_DIR [ENV_DIR ...]
> 
> venv: error: the following arguments are required: ENV_DIR
> 
> ./quick_start.sh: line 11: venv/bin/activate: No such file or directory
> 
> Defaulting to user installation because normal site-packages is not writeable
> 
> Requirement already satisfied: SQLAlchemy==1.3.11 in /home/mahmud/.local/lib/python3.9/site-packages (from -r requirements.txt (line 1)) (1.3.11)
> 
> Requirement already satisfied: sqlalchemy-migrate==0.13.0 in /home/mahmud/.local/lib/python3.9/site-packages (from -r requirements.txt (line 2)) (0.13.0)
> 
> Requirement already satisfied: Telethon==1.23.0 in /home/mahmud/.local/lib/python3.9/site-packages (from -r requirements.txt (line 3)) (1.23.0)
> 
> Requirement already satisfied: mysql-connector-python==8.0.18 in /home/mahmud/.local/lib/python3.9/site-packages (from -r requirements.txt (line 4)) (8.0.18)
> 
> Requirement already satisfied: gspread==3.1.0 in /home/mahmud/.local/lib/python3.9/site-packages (from -r requirements.txt (line 5)) (3.1.0)
> 
> Requirement already satisfied: oauth2client==4.1.3 in /home/mahmud/.local/lib/python3.9/site-packages (from -r requirements.txt (line 6)) (4.1.3)
> 
> Requirement already satisfied: python-dotenv==0.19.0 in /home/mahmud/.local/lib/python3.9/site-packages (from -r requirements.txt (line 7)) (0.19.0)
> 
> Requirement already satisfied: requests>=2.2.1 in /usr/lib/python3.9/site-packages (from gspread==3.1.0->-r requirements.txt (line 5)) (2.26.0)
> 
> Requirement already satisfied: protobuf>=3.0.0 in /home/mahmud/.local/lib/python3.9/site-packages (from mysql-connector-python==8.0.18->-r requirements.txt (line 4)) (3.17.3)
> 
> Requirement already satisfied: rsa>=3.1.4 in /home/mahmud/.local/lib/python3.9/site-packages (from oauth2client==4.1.3->-r requirements.txt (line 6)) (4.7.2)
> 
> Requirement already satisfied: pyasn1>=0.1.7 in /home/mahmud/.local/lib/python3.9/site-packages (from oauth2client==4.1.3->-r requirements.txt (line 6)) (0.4.8)
> 
> Requirement already satisfied: pyasn1-modules>=0.0.5 in /home/mahmud/.local/lib/python3.9/site-packages (from oauth2client==4.1.3->-r requirements.txt (line 6)) (0.2.8)
> 
> Requirement already satisfied: httplib2>=0.9.1 in /home/mahmud/.local/lib/python3.9/site-packages (from oauth2client==4.1.3->-r requirements.txt (line 6)) (0.19.1)
> 
> Requirement already satisfied: six>=1.6.1 in /usr/lib/python3.9/site-packages (from oauth2client==4.1.3->-r requirements.txt (line 6)) (1.16.0)
> 
> Requirement already satisfied: pbr>=1.8 in /home/mahmud/.local/lib/python3.9/site-packages (from sqlalchemy-migrate==0.13.0->-r requirements.txt (line 2)) (5.6.0)
> 
> Requirement already satisfied: Tempita>=0.4 in /home/mahmud/.local/lib/python3.9/site-packages (from sqlalchemy-migrate==0.13.0->-r requirements.txt (line 2)) (0.5.2)
> 
> Requirement already satisfied: sqlparse in /home/mahmud/.local/lib/python3.9/site-packages (from sqlalchemy-migrate==0.13.0->-r requirements.txt (line 2)) (0.4.1)
> 
> Requirement already satisfied: decorator in /home/mahmud/.local/lib/python3.9/site-packages (from sqlalchemy-migrate==0.13.0->-r requirements.txt (line 2)) (5.0.9)
> 
> Requirement already satisfied: pyaes in /home/mahmud/.local/lib/python3.9/site-packages (from Telethon==1.23.0->-r requirements.txt (line 3)) (1.6.1)
> 
> Requirement already satisfied: pyparsing<3,>=2.4.2 in /usr/lib/python3.9/site-packages (from httplib2>=0.9.1->oauth2client==4.1.3->-r requirements.txt (line 6)) (2.4.7)
> 
> Requirement already satisfied: chardet>=3.0.2 in /usr/lib/python3.9/site-packages (from requests>=2.2.1->gspread==3.1.0->-r requirements.txt (line 5)) (4.0.0)
> 
> Requirement already satisfied: idna>=2.5 in /usr/lib/python3.9/site-packages (from requests>=2.2.1->gspread==3.1.0->-r requirements.txt (line 5)) (3.2)
> 
> Requirement already satisfied: urllib3>=1.21.1 in /usr/lib/python3.9/site-packages (from requests>=2.2.1->gspread==3.1.0->-r requirements.txt (line 5)) (1.26.6)
> 
> INFO:root:env_file: informer.env
> 
> INFO:telethon.crypto.aes:libssl detected, it will be used for encryption
> 
> Traceback (most recent call last):
> 
> File "/home/mahmud/Downloads/informer-master/app/bot.py", line 33, in <module>
> 
> account_id = sys.argv[1]
> 
> IndexError: list index out of range
> 
> During handling of the above exception, another exception occurred:
> 
> 
> Traceback (most recent call last):
> File "/home/mahmud/Downloads/informer-master/app/bot.py", line 35, in <module>
> raise Exception('informer.py <account_id> - account_id is a required param')
> Exception: informer.py <account_id> - account_id is a required param
> 
> `

the same problem that i sloved by modify quick_start.sh in line8:
python3 -m venv venv

please insure your python3 version >3.7
