### ISSUE TITLE
All the problems I encountered when running this plugin in a ubuntu 22.04 virtual machine on a windows system with vmware installed

### ISSUE THREAD

**Issue by zbossz** [paulpierre/informer#14]
Traceback (most recent call last):
  File "/home/informer-master/app/bot.py", line 35, in <module>
    raise Exception('informer.py <account_id> - account_id is a required param')
Exception: informer.py <account_id> - account_id is a required param

but i already finished the informer.env

**Comment by zbossz** [comment]
I directly assign the account_id of /homeyinformer-master/app/bot'py to the exact id, instead of getting it from the metric

**Comment by zbossz** [comment]
sqlalchemy.exc.InterfaceError: (mysql.connector.errors.InterfaceError) 2003: Can't connect to MySQL server on 'docker.for.mac.localhost:3307' (111 Connection refused)
(Background on this error at: http://sqlalche.me/e/rvf5)

new issue came out

**Comment by zbossz** [comment]
I solved the problem by installing mysql locally and running it, and changing the informer.env port to the default 3306

**Comment by zbossz** [comment]
I not only changed the port, but also changed the mysq| user name to my own, and the address is localhost, not docker.mac.xxxxxxx

**Comment by zbossz** [comment]
new problem here:
Traceback (most recent call last):
  File "/home/informer-master1/app/bot.py", line 42, in <module>
    informer = TGInformer(
  File "/home/informer-master1/app/informer.py", line 145, in __init__
    self.loop.run_until_complete(self.bot_interval())
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/informer-master1/app/informer.py", line 642, in bot_interval
    self.client = TelegramClient(session_file, self.account.account_api_id, self.account.account_api_hash)
  File "/usr/local/lib/python3.10/dist-packages/telethon/client/telegrambaseclient.py", line 262, in __init__
    session = SQLiteSession(session)
  File "/usr/local/lib/python3.10/dist-packages/telethon/sessions/sqlite.py", line 47, in __init__
    c = self._cursor()
  File "/usr/local/lib/python3.10/dist-packages/telethon/sessions/sqlite.py", line 228, in _cursor
    self._conn = sqlite3.connect(self.filename,
sqlite3.OperationalError: unable to open database file

I created my own informer_db database in mysql under the root user.
Maybe that's the problem.

**Comment by zbossz** [comment]
https://stackoverflow.com/questions/76620568/when-i-use-https-github-com-paulpierre-informer-for-this-project-i-encountere

I have been able to run the software successfully, I suggest you refer to this link to troubleshoot the error

**Comment by zbossz** [comment]
So far I can still only run quick_start.sh

**Comment by zbossz** [comment]
after i run ./start.sh
```
INFO:root:init_monitor_channels: Monitoring channels: []
app_informer    | INFO:root:Channel METADATA: {}
app_informer    | INFO:root:### {count} Running bot interval
app_informer    | INFO:root:init_keywords: Monitoring keywords: [
app_informer    |     {
app_informer    |         "id": 1,
app_informer    |         "name": "Binance",
app_informer    |         "regex": "(binance|bnb)"
app_informer    |     }
app_informer    | ]
app_informer    | INFO:root:init_keywords: Monitoring keywords: [
app_informer    |     {
app_informer    |         "id": 1,
app_informer    |         "name": "Binance",
app_informer    |         "regex": "(binance|bnb)"
app_informer    |     },
app_informer    |     {
app_informer    |         "id": 2,
app_informer    |         "name": "Huobi",
app_informer    |         "regex": "(huobi)"
app_informer    |     }
app_informer    | ]
app_informer    | INFO:root:init_keywords: Monitoring keywords: [
app_informer    |     {
app_informer    |         "id": 1,
app_informer    |         "name": "Binance",
app_informer    |         "regex": "(binance|bnb)"
app_informer    |     },
app_informer    |     {
app_informer    |         "id": 2,
app_informer    |         "name": "Huobi",
app_informer    |         "regex": "(huobi)"
app_informer    |     },
app_informer    |     {
app_informer    |         "id": 3,
app_informer    |         "name": "Bittrex",
app_informer    |         "regex": "(bittrex)"
app_informer    |     }
app_informer    | ]
app_informer    | INFO:root:init_keywords: Monitoring keywords: [
app_informer    |     {
app_informer    |         "id": 1,
app_informer    |         "name": "Binance",
app_informer    |         "regex": "(binance|bnb)"
app_informer    |     },
app_informer    |     {
app_informer    |         "id": 2,
app_informer    |         "name": "Huobi",
app_informer    |         "regex": "(huobi)"
app_informer    |     },
app_informer    |     {
app_informer    |         "id": 3,
app_informer    |         "name": "Bittrex",
app_informer    |         "regex": "(bittrex)"
app_informer    |     },
app_informer    |     {
app_informer    |         "id": 4,
app_informer    |         "name": "Bitfinex",
app_informer    |         "regex": "(bitfinex)"
app_informer    |     }
app_informer    | ]
app_informer    | INFO:root:init_keywords: Monitoring keywords: [
app_informer    |     {
app_informer    |         "id": 1,
app_informer    |         "name": "Binance",
app_informer    |         "regex": "(binance|bnb)"
app_informer    |     },
app_informer    |     {
app_informer    |         "id": 2,
app_informer    |         "name": "Huobi",
app_informer    |         "regex": "(huobi)"
app_informer    |     },
app_informer    |     {
app_informer    |         "id": 3,
app_informer    |         "name": "Bittrex",
app_informer    |         "regex": "(bittrex)"
app_informer    |     },
app_informer    |     {
app_informer    |         "id": 4,
app_informer    |         "name": "Bitfinex",
app_informer    |         "regex": "(bitfinex)"
app_informer    |     },
app_informer    |     {
app_informer    |         "id": 5,
app_informer    |         "name": "Coinbase",
app_informer    |         "regex": "(coinbase)"
app_informer    |     }
app_informer    | ]
app_informer    | INFO:root:init_keywords: Monitoring keywords: [
app_informer    |     {
app_informer    |         "id": 1,
app_informer    |         "name": "Binance",
app_informer    |         "regex": "(binance|bnb)"
app_informer    |     },
app_informer    |     {
app_informer    |         "id": 2,
app_informer    |         "name": "Huobi",
app_informer    |         "regex": "(huobi)"
app_informer    |     },
app_informer    |     {
app_informer    |         "id": 3,
app_informer    |         "name": "Bittrex",
app_informer    |         "regex": "(bittrex)"
app_informer    |     },
app_informer    |     {
app_informer    |         "id": 4,
app_informer    |         "name": "Bitfinex",
app_informer    |         "regex": "(bitfinex)"
app_informer    |     },
app_informer    |     {
app_informer    |         "id": 5,
app_informer    |         "name": "Coinbase",
app_informer    |         "regex": "(coinbase)"
app_informer    |     },
app_informer    |     {
app_informer    |         "id": 6,
app_informer    |         "name": "Kraken",
app_informer    |         "regex": "(kraken)"
app_informer    |     }
app_informer    | ]
app_informer    | INFO:root:init_keywords: Monitoring keywords: [
app_informer    |     {
app_informer    |         "id": 1,
app_informer    |         "name": "Binance",
app_informer    |         "regex": "(binance|bnb)"
app_informer    |     },
app_informer    |     {
app_informer    |         "id": 2,
app_informer    |         "name": "Huobi",
app_informer    |         "regex": "(huobi)"
app_informer    |     },
app_informer    |     {
app_informer    |         "id": 3,
app_informer    |         "name": "Bittrex",
app_informer    |         "regex": "(bittrex)"
app_informer    |     },
app_informer    |     {
app_informer    |         "id": 4,
app_informer    |         "name": "Bitfinex",
app_informer    |         "regex": "(bitfinex)"
app_informer    |     },
app_informer    |     {
app_informer    |         "id": 5,
app_informer    |         "name": "Coinbase",
app_informer    |         "regex": "(coinbase)"
app_informer    |     },
app_informer    |     {
app_informer    |         "id": 6,
app_informer    |         "name": "Kraken",
app_informer    |         "regex": "(kraken)"
app_informer    |     },
app_informer    |     {
app_informer    |         "id": 7,
app_informer    |         "name": "Poloniex",
app_informer    |         "regex": "(poloniex)"
app_informer    |     }
app_informer    | ]
```
nothing happened in mysql tables.
