### ISSUE TITLE
Problem with running a local docker image

### ISSUE THREAD

**Issue by capita-davidwoakes** [paulpierre/informer#6]
I built an image OK but when I run it using

docker run my:tag

I get the following:

```
            ____      ____
           /  _/___  / __/___  _________ ___  ___  _____
           / // __ \/ /_/ __ \/ ___/ __ `__ \/ _ \/ ___/
         _/ // / / / __/ /_/ / /  / / / / / /  __/ /
        /___/_/ /_/_/  \____/_/  /_/ /_/ /_/\___/_/

        by @paulpierre 11-26-2019

INFO:root:SERVER_MODE: prod GAE_ENV: prod
Traceback (most recent call last):
  File "bot.py", line 23, in <module>
    informer = TGInformer(
  File "/usr/informer/informer.py", line 114, in __init__
    creds = ServiceAccountCredentials.from_json_keyfile_name(google_credentials_path, scope)
  File "/usr/local/lib/python3.8/site-packages/oauth2client/service_account.py", line 219, in from_json_keyfile_name
    with open(filename, 'r') as file_obj:
FileNotFoundError: [Errno 2] No such file or directory: 'credentials/gcloud_api.json'
```

**Comment by paulpierre** [comment]
You have to generate your json credentials file if you want to run on Google App Engine:

https://cloud.google.com/iam/docs/creating-managing-service-account-keys
